name: Pipeline

on: push

jobs:
  code-quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run ruff
        run: |
          poetry run pre-commit run -a 

  run-tests:
    needs: code-quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run tests for image builds with pytest
        env:
          KEYCLOAK_VERSION: 26.0.7
          POSTGRESQL_VERSION: 17.2
        run: |
          poetry run pytest --cov build --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
